# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-06 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cnpj',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='insc',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
