# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-06 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordem', '0004_auto_20180403_0435'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordens',
            name='carro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ordens',
            name='placa',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='ordens',
            name='desc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
