# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-06 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordem', '0005_auto_20180406_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordens',
            name='metodo',
            field=models.CharField(blank=True, choices=[('1', 'Dinheiro'), ('2', 'Cartao Debito'), ('3', 'Cartao Credito')], max_length=1, null=True),
        ),
    ]
